// build-roots.mjs — DPD root import pipeline.
//
// Reads the Digital Pāḷi Dictionary roots backup (dpd_roots.tsv), merges in our
// curated Chinese glosses + present-stem forms, and writes ../roots.data.js
// (consumed by roots.js). Run: node tools/build-roots.mjs
//
// Re-fetch the source first with:
//   curl -sS -o tools/dpd_cache/dpd_roots.tsv \
//     https://raw.githubusercontent.com/digitalpalidictionary/dpd-db/main/db/backup_tsv/dpd_roots_part_001.tsv
//
// Data source: Digital Pāḷi Dictionary (dpd-db), CC BY-NC-SA. English meanings
// are DPD's `root_meaning`. Chinese is from tools/curated-roots.mjs (ours).

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { CURATED } from './curated-roots.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

// --- parse the quoted TSV ---------------------------------------------------
const tsv = readFileSync(join(here, 'dpd_cache', 'dpd_roots.tsv'), 'utf8');
const lines = tsv.split('\n').filter((l) => l.length);
const header = splitRow(lines[0]);
const col = (name) => header.indexOf(name);
const C_ROOT = col('root');
const C_MEAN = col('root_meaning');
const C_VERB = col('root_has_verb');

function splitRow(line) {
  // fields are wrapped in double quotes and tab-separated; "" escapes a quote
  return line.split('\t').map((f) => f.replace(/^"|"$/g, '').replace(/""/g, '"').trim());
}

// --- curated overlay (zh + present-stem forms), keyed by bare root ----------
const curatedMap = new Map();
for (const d of CURATED) curatedMap.set(d.root, d);

// --- merge ------------------------------------------------------------------
const byRoot = new Map(); // bareRoot -> { root, forms:Set, en:Set, zh }
for (let i = 1; i < lines.length; i++) {
  const f = splitRow(lines[i]);
  const raw = f[C_ROOT] || '';
  const bare = raw.replace(/^√/, '').replace(/\s+\d+$/, '').trim();
  if (!bare) continue;
  const meaning = (f[C_MEAN] || '').trim();
  if (!byRoot.has(bare)) byRoot.set(bare, { root: bare, forms: new Set([bare]), en: new Set(), zh: '' });
  const e = byRoot.get(bare);
  if (meaning && meaning !== '-') e.en.add(meaning);
}

// overlay curated zh + extra forms; also add curated-only roots
for (const d of CURATED) {
  if (!byRoot.has(d.root)) byRoot.set(d.root, { root: d.root, forms: new Set(d.forms), en: new Set(), zh: d.zh });
  const e = byRoot.get(d.root);
  e.zh = d.zh || e.zh;
  for (const form of d.forms) e.forms.add(form);
  if (d.en) e.en.add(d.en);
}

// --- emit -------------------------------------------------------------------
const DHATU = [...byRoot.values()]
  .sort((a, b) => a.root.localeCompare(b.root))
  .map((e) => ({
    root: e.root,
    forms: [...e.forms],
    en: [...e.en].join('; ') || 'to ' + e.root,
    zh: e.zh || '',
  }));

const out =
  '// roots.data.js — GENERATED by tools/build-roots.mjs. Do not edit by hand.\n' +
  '// ' + DHATU.length + ' Pāli verbal roots. English from the Digital Pāḷi\n' +
  '// Dictionary (dpd-db, CC BY-NC-SA); Chinese + verb stems from curated-roots.mjs.\n' +
  '(function (global) {\n' +
  '  \'use strict\';\n' +
  '  const DHATU = ' + JSON.stringify(DHATU) + ';\n' +
  '  const DATA = { DHATU };\n' +
  '  if (typeof module !== \'undefined\' && module.exports) module.exports = DATA;\n' +
  '  global.PaliRootsData = DATA;\n' +
  '})(typeof globalThis !== \'undefined\' ? globalThis : this);\n';

writeFileSync(join(root, 'roots.data.js'), out);

const withZh = DHATU.filter((d) => d.zh).length;
console.log(`wrote roots.data.js: ${DHATU.length} roots (${withZh} with 中文, ${DHATU.length - withZh} English-only)`);
